/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DepartmentEntity
 */
export interface DepartmentEntity {
  /**
   *
   * @type {string}
   * @memberof DepartmentEntity
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof DepartmentEntity
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof DepartmentEntity
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof DepartmentEntity
   */
  description?: string;
  /**
   *
   * @type {DepartmentEntity}
   * @memberof DepartmentEntity
   */
  parent: DepartmentEntity;
}
