/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 角色数据实体
 * @export
 * @interface RoleEntity
 */
export interface RoleEntity {
  /**
   * 角色ID
   * @type {string}
   * @memberof RoleEntity
   */
  id?: string;
  /**
   * 角色代码
   * @type {string}
   * @memberof RoleEntity
   */
  code: string;
  /**
   * 角色名称
   * @type {string}
   * @memberof RoleEntity
   */
  name: string;
  /**
   * 角色描述
   * @type {string}
   * @memberof RoleEntity
   */
  description?: string;
}
