/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DictionaryEntity } from '/@/apis/dictionaries';
/**
 * 字典项数据实体
 * @export
 * @interface DictionaryItemEntity
 */
export interface DictionaryItemEntity {
  /**
   * 主键ID
   * @type {string}
   * @memberof DictionaryItemEntity
   */
  id: string;
  /**
   * 字典项名称
   * @type {string}
   * @memberof DictionaryItemEntity
   */
  name: string;
  /**
   * 字典项内容
   * @type {string}
   * @memberof DictionaryItemEntity
   */
  content: string;
  /**
   *
   * @type {DictionaryEntity}
   * @memberof DictionaryItemEntity
   */
  dictionary: DictionaryEntity;
}
